version: '3'
services:
  mongo:
    env_file:
      - .env.dev
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
#  mongo-express:
#    image: mongo-express:0.54
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
  fastapi:
    env_file:
      - .env.dev
    build:
      context: ./
    volumes:
      - './analyzer:/app'
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug